language: python

python:
  - "2.7"
  - "3.5"
  - "3.6"
  - "3.7"
  - "3.8"

before_install:
  - deactivate
  - sudo pip install --upgrade pip

install:
  # removing binary libs for the moment
  #- sudo apt-get install libopenblas-dev liblapack-dev gfortran
  - xargs -a requirements.txt -n 1 pip install --user
  - pip install pytest
  - pip install pylint

script:
  - pytest
  - pylint mmacommon


branches:
  only:
    - master
    - stable
